<?php
$typeArr[1] = '企业简介';
$typeArr[23] = '摄像机';
$typeArr[24] = '硬盘录像机';
$typeArr[2] = '资质荣誉';
$typeArr[3] = '售后服务';
$typeArr[4] = '联系我们';
$typeArr[5] = '新闻资讯';
$typeArr[6] = '企业新闻';
$typeArr[7] = '行业新闻';
$typeArr[8] = '产品展示';
$typeArr[9] = '视频监控系统';
$typeArr[10] = '防盗报警系统';
$typeArr[11] = '楼宇对讲系统';
$typeArr[12] = '一卡通系统';
$typeArr[13] = '服务支持';
$typeArr[14] = '产品帮助';
$typeArr[15] = '软件下载';
$typeArr[16] = '案例展示';
$typeArr[19] = '人才招聘';
$typeArr[20] = '社会招聘';
$typeArr[21] = '校园招聘';
$typeArr[22] = '联系我们';
$typeArr[26] = '监控配件';
$typeArr[27] = '红外对射';
$typeArr[28] = '红外探测器';
$typeArr[29] = '报警主机';
?>