<div class="sub-title  b">
                                            [field:title/]</div>
                                        <div class="column-box-description paddingT05">
                                            {dede:field.description/}...
                                        </div>
                                        <div class="read-more">
                                            <a href="[field:arcurl/]">了解更多
                                                &raquo;</a></div>
                                        <div class="articles_horizontal_divider">
                                            <img src="../../Images/articles_divider_long.png" />
                                        </div>