<li class="product-item">
                    <div class="product-image">
                        <a href="[field:arcurl/]">
                            <img src="[field:picname/]" alt="[field:title/]" title="[field:title/]" /></a></div>
                    <div class="product-description">
                        <div class="product-header blue-dark ">
                            <img src="[field:biaotu/]" width="" height="30" alt="[field:title/]" title="[field:title/]" /></div>
                        <div class="product-divider">
                        </div>
                        <div class="product-text gold f_mhgb">
                           [field:shorttitle/]
                        
                    </div>
                        </div>
                    <div class="product-button item_desktop item_960">
                        <div class="button btn-175">
                            <a href="[field:arcurl/]">了解更多</a>
                            <div class="arrow">
                            </div>
                        </div>
                    </div>
                </li>