<field:biaotu itemname="标题图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:biaotu>
<field:guanyubaobao itemname="关于宝宝" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:guanyubaobao>
<field:guanyumama itemname="关于妈妈" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:guanyumama>
<field:guanyubaba itemname="关于爸爸" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:guanyubaba>
<field:xiangguancpt itemname="相关产品图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xiangguancpt>
<field:xiangguancpbtt itemname="相关产品标题图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xiangguancpbtt>
<field:xiangguancpbt itemname="相关产品标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xiangguancpbt>
<field:xiangguancpjdbt itemname="相关产品简短标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xiangguancpjdbt>
<field:xiangguancplj itemname="相关产品链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xiangguancplj>
