<?php
$z[0]=Array("field","",257,280);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",607,641);
$z[3][4]['filename']="top.htm";
$z[4]=Array("global","",828,853);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("field","",2199,2228);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n		 <div class='ej_lnav' id='ejnav55'><a href='[field:typeurl/]'   target=\"\"  title=\"[field:typename/]\">[field:typename/]</a></div><div class='ss' id='s55'></div>\r\n",2258,2463);
$z[6][4]['type']="son";
$z[7]=Array("field","",3507,3526);
$z[7][4]['name']="title";
$z[8]=Array("field","",3626,3655);
$z[8][4]['name']="position";
$z[9]=Array("field","",3771,3792);
$z[9][4]['name']="content";
$z[10]=Array("include","",4971,5005);
$z[10][4]['filename']="bom.htm";

?>