<?php
$z[0]=Array("field","",257,280);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",321,350);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",390,448);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",607,641);
$z[3][4]['filename']="top.htm";
$z[4]=Array("global","",828,853);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("tag","<a href=\"'[field:link/]\">[field:tag /]</a> ",1429,1524);
$z[5][4]['row']="7";
$z[5][4]['sort']="new";
$z[5][4]['getall']="1";
$z[6]=Array("field","",1735,1764);
$z[6][4]['name']="typename";
$z[7]=Array("channel","\r\n		 <div class='ej_lnav' id='ejnav55'><a href='[field:typeurl/]'   target=\"\"  title=\"[field:typename/]\">[field:typename/]</a></div><div class='ss' id='s55'></div>\r\n",1794,2000);
$z[7][4]['type']="son";
$z[8]=Array("field","",3050,3069);
$z[8][4]['name']="title";
$z[9]=Array("field","",3169,3198);
$z[9][4]['name']="position";
$z[10]=Array("list","\r\n                    <div class=\"product_ctr\">\r\n                        <div class=\"product_ctt\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img alt=\"[field:title /]\" src=\"[field:picname/]\" width=\"160\" height=\"116\"></a></div>\r\n                        <div class='product_title'><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div>\r\n                        \r\n                    </div>\r\n",3375,3825);
$z[10][4]['pagesize']="8";
$z[11]=Array("pagelist","",3920,3991);
$z[11][4]['listitem']="info,index,end,pre,next,pageno";
$z[11][4]['listsize']="5";
$z[12]=Array("include","",4079,4113);
$z[12][4]['filename']="bom.htm";

?>