<?php
$z[0]=Array("field","",1099,1122);
$z[0][4]['name']="seotitle";
$z[1]=Array("include","",1325,1359);
$z[1][4]['filename']="top.htm";
$z[2]=Array("field","",2149,2178);
$z[2][4]['name']="typename";
$z[3]=Array("field","",3145,3174);
$z[3][4]['name']="typename";
$z[4]=Array("field","",3182,3203);
$z[4][4]['name']="content";
$z[5]=Array("include","",3745,3779);
$z[5][4]['filename']="bom.htm";

?>