<div class="product_ctr1">
                        <div class="product_ctt1"><a href="[field:arcurl/]" title="[field:title/]"><img alt="[field:title /]" src="[field:picname/]" width="210" height="155"></a></div>
                        <div class="product_title1"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a><br />[field:description function='cn_substr(@me,70)'/]...</div>
                        <div class="product_more"><span><a href="[field:arcurl/]">了解详情+</a></span></div>
                    </div>