
<field:guanyubaobao itemname="关于宝宝" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:guanyubaobao>

<field:guanyumama itemname="关于妈妈" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:guanyumama>

<field:guanyubaba itemname="关于爸爸" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:guanyubaba>
