<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:datu itemname="大图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:datu>
<field:biaotu itemname="标题图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:biaotu>
<field:goumai itemname="购买链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:goumai>
<field:tujieshao itemname="图片介绍" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tujieshao>
