<?php
$z[0]=Array("field","",254,277);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",318,347);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",387,445);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",604,638);
$z[3][4]['filename']="top.htm";
$z[4]=Array("global","",825,850);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("field","",2196,2225);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n		 <div class='ej_lnav' id='ejnav55'><a href='[field:typeurl/]'   target=\"\"  title=\"[field:typename/]\">[field:typename/]</a></div><div class='ss' id='s55'></div>\r\n",2255,2461);
$z[6][4]['type']="son";
$z[7]=Array("field","",3511,3530);
$z[7][4]['name']="title";
$z[8]=Array("field","",3630,3659);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n                    <div class=\"product_ctr1\">\r\n                        <div class=\"product_ctt1\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img alt=\"[field:title /]\" src=\"[field:picname/]\" width=\"210\" height=\"155\"></a></div>\r\n                        <div class=\"product_title1\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><br />[field:description function='cn_substr(@me,70)'/]...</div>\r\n                        <div class=\"product_more\"><span><a href=\"[field:arcurl/]\">了解详情+</a></span></div>\r\n                    </div>\r\n\r\n",3856,4457);
$z[9][4]['pagesize']="6";
$z[10]=Array("pagelist","",4577,4648);
$z[10][4]['listitem']="info,index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",5138,5172);
$z[11][4]['filename']="bom.htm";

?>