<?php
$z[0]=Array("global","",263,318);
$z[0][4]['name']="keyword";
$z[0][4]['function']="RemoveXSS(@me)";
$z[1]=Array("field","",369,398);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",438,496);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",655,689);
$z[3][4]['filename']="top.htm";
$z[4]=Array("global","",876,901);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("likewords","",2342,2367);
$z[5][4]['num']="8";
$z[6]=Array("global","",3441,3496);
$z[6][4]['name']="keyword";
$z[6][4]['function']="RemoveXSS(@me)";
$z[7]=Array("field","",3609,3638);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                    <div class=\"newslist_ctr\">\r\n                        <div class=\"newslist_title\">·<a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div><div class=\"newslist_date\">[field:pubdate function=\"GetDateMK(@me)\"/]</div>\r\n                    </div>\r\n",3708,4026);
$z[8][4]['perpage']="20";
$z[9]=Array("pagelist","",4067,4096);
$z[9][4]['listsize']="4";
$z[10]=Array("include","",4184,4218);
$z[10][4]['filename']="bom.htm";

?>