<?php
$z[0]=Array("global","",619,646);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",836,863);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",3662,3689);
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("type","<a title=\"菜单_[field:typename /]\" href=\"[field:typelink /]\"></a>",3816,3917);
$z[3][4]['typeid']="1";
$z[4]=Array("type","<a title=\"菜单_[field:typename /]\" href=\"[field:typelink /]\"></a>",4051,4152);
$z[4][4]['typeid']="2";
$z[5]=Array("type","<a title=\"菜单_[field:typename /]\" href=\"[field:typelink /]\"></a>",4285,4386);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<a title=\"菜单_[field:typename /]\" href=\"[field:typelink /]\"></a>",4502,4604);
$z[6][4]['typeid']="15";
$z[7]=Array("type","<a title=\"菜单_[field:typename /]\" href=\"[field:typelink /]\"></a>",4729,4831);
$z[7][4]['typeid']="14";
$z[8]=Array("type","<a title=\"菜单_[field:typename /]\" href=\"[field:typelink /]\"></a>",4954,5056);
$z[8][4]['typeid']="19";
$z[9]=Array("arclist"," \r\n                            <li><a title=\"菜单_二级_[field:title /]\" href=\"[field:arcurl /]\">\r\n                                <div class=\"b nav-header\">\r\n                                    [field:title /]</div>\r\n                                <div class=\"\">\r\n                                    [field:array runphp='yes'] if(@me['shorttitle']==”) @me=@me['title'];else @me=@me['shorttitle'];[/field:array]</div>\r\n                            </a></li>\r\n						",5393,5926);
$z[9][4]['typeid']="2";
$z[9][4]['titlelen']="40";
$z[9][4]['row']="4";
$z[10]=Array("arclist"," \r\n                            <li><a title=\"菜单_二级[field:title /]\" href=\"[field:arcurl /]\">\r\n                                <div class=\"b nav-header\">\r\n                                    [field:title /]</div>\r\n                            </a></li>\r\n						",6161,6489);
$z[10][4]['typeid']="3";
$z[10][4]['titlelen']="40";
$z[10][4]['row']="4";
$z[11]=Array("channel","\r\n                            <li><a title=\"菜单_二级_[field:typename/]\" href=\"[field:typelink/]\">\r\n                                <div class=\"b nav-header\">\r\n                                    [field:typename/]</div>\r\n                            </a></li>\r\n						",6654,6984);
$z[11][4]['type']="son";
$z[11][4]['typeid']="15";
$z[11][4]['row']="4";

?>