<?php
$z[0]=Array("global","",975,1002);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename /]\">[field:typename /]</a>",1181,1294);
$z[1][4]['typeid']="1";
$z[2]=Array("channel","\r\n                    <div class=\"ej_nav\"><a href=\"[field:typelink/]\"  target=\"\" title=\"[field:typename/]\">[field:typename/]</a></div>\r\n                ",1428,1631);
$z[2][4]['type']="son";
$z[2][4]['typeid']="1";
$z[3]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename /]\">[field:typename /]</a>",1851,1964);
$z[3][4]['typeid']="5";
$z[4]=Array("channel","\r\n                    <div class=\"ej_nav\"><a href=\"[field:typelink/]\"  target=\"\" title=\"[field:typename/]\">[field:typename/]</a></div>\r\n                ",2113,2316);
$z[4][4]['type']="son";
$z[4][4]['typeid']="5";
$z[5]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename /]\">[field:typename /]</a>",2539,2652);
$z[5][4]['typeid']="8";
$z[6]=Array("channelartlist","\r\n                <div class=\"ej_nav1\">\r\n                    <div class=\"ej_nav11\">{dede:field name='typename'/}：</div>\r\n                    <div class=\"ej_nav12\">{dede:sql sql='Select * from dede_arctype where reid=~id~ ORDER BY id limit 0,7'}<a href=\"[field:typedir/]\">[field:typename/]</a> | {/dede:sql}</div>\r\n                </div>\r\n			",2794,3201);
$z[6][4]['typeid']="8";
$z[6][4]['row']="4";
$z[7]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename /]\">[field:typename /]</a>",3406,3520);
$z[7][4]['typeid']="13";
$z[8]=Array("channel","\r\n                    <div class=\"ej_nav\"><a href=\"[field:typelink/]\"  target=\"\" title=\"[field:typename/]\">[field:typename/]</a></div>\r\n                ",3672,3876);
$z[8][4]['type']="son";
$z[8][4]['typeid']="13";
$z[9]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename /]\">[field:typename /]</a>",4099,4213);
$z[9][4]['typeid']="16";
$z[10]=Array("channel","\r\n                    <div class=\"ej_nav\"><a href=\"[field:typelink/]\"  target=\"\" title=\"[field:typename/]\">[field:typename/]</a></div>\r\n                ",4365,4569);
$z[10][4]['type']="son";
$z[10][4]['typeid']="16";
$z[11]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename /]\">[field:typename /]</a>",4792,4906);
$z[11][4]['typeid']="19";
$z[12]=Array("channel","\r\n                    <div class=\"ej_nav\"><a href=\"[field:typelink/]\"  target=\"\" title=\"[field:typename/]\">[field:typename/]</a></div>\r\n                ",5058,5262);
$z[12][4]['type']="son";
$z[12][4]['typeid']="19";
$z[13]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename /]\">[field:typename /]</a>",5485,5599);
$z[13][4]['typeid']="22";

?>